#!/bin/bash

echo "🧪 Tests Mixpanel - Guide de vérification"
echo "=========================================="
echo ""
echo "✅ Phase 1: SDK installé et initialisé"
echo ""
echo "📋 Pour tester l'événement 'onboarding_welcome_viewed':"
echo "1. Lance l'app sur simulateur"
echo "2. Déconnecte-toi si connecté (Settings > Déconnexion)"
echo "3. Clique sur 'Sign Up' pour créer un nouveau compte"
echo "4. L'écran FirstLaunchWelcomeView devrait s'afficher"
echo "5. Dans la console Xcode, cherche: '[Mixpanel] 📊 Event: onboarding_welcome_viewed'"
echo ""
echo "6. Clique sur 'Commencer' après 5-10 secondes"
echo "7. Dans la console, cherche: '[Mixpanel] 📊 Event: onboarding_welcome_continue'"
echo "   avec la propriété 'time_spent' (devrait être ~5-10 secondes)"
echo ""
echo "📊 Vérifier dans le dashboard Mixpanel:"
echo "1. Va sur https://eu.mixpanel.com/project/3310694"
echo "2. Clique sur 'Events' dans le menu de gauche"
echo "3. Tu devrais voir apparaître (peut prendre 1-2 minutes):"
echo "   - onboarding_welcome_viewed"
echo "   - onboarding_welcome_continue"
echo ""
echo "4. Clique sur un événement pour voir les propriétés:"
echo "   Super properties (sur tous les événements):"
echo "   - app_version"
echo "   - os_version"
echo "   - device_type (iPhone Simulator)"
echo "   - language (fr)"
echo "   - platform (iOS)"
echo ""
echo "   Propriétés spécifiques à 'onboarding_welcome_continue':"
echo "   - time_spent (en secondes)"
echo ""
echo "🔍 Événements suivants à implémenter:"
echo "   - onboarding_quiz_started (HabitsQuizView)"
echo "   - task_validated (TasksV2View)"
echo "   - achievement_unlocked (ProfileView)"
echo ""
