#!/usr/bin/env python3
"""Integrate the narration drafts into the app.

1. Merges drafts/<theme>.<lang>.json into Resources/Narration/narration_<lang>.json
   (drafted sessions replace existing ones, untouched sessions are kept).
2. Generates Models/Audio/GuidedSessionCatalogData.swift from catalog_plan.json:
   the session list and the theme titles/subtitles. A session is only included
   once it has a French script, so the app never lists a session it can't play.

Usage: python3 build_catalog.py
"""
import json, os, re, glob

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.normpath(os.path.join(HERE, "../../CortiFree/CortiFree"))
NARRATION = os.path.join(APP, "Resources/Narration")
CATALOG_SWIFT = os.path.join(APP, "Models/Audio/GuidedSessionCatalog.swift")
OUT_SWIFT = os.path.join(APP, "Models/Audio/GuidedSessionCatalogData.swift")
LANGS = ["fr", "en", "de", "es", "ja", "ko"]
AMBIENCES = {"rain", "ocean", "fire", "whitenoise", "morning", "forest", "stream", "summerNight"}

plan = json.load(open(os.path.join(HERE, "catalog_plan.json"), encoding="utf-8"))


def merge_narration(lang):
    path = os.path.join(NARRATION, f"narration_{lang}.json")
    if os.path.exists(path):
        data = json.load(open(path, encoding="utf-8"))
    else:
        data = {"language": lang, "version": 2,
                "voiceDirection": "Warm, calm, intimate voice. Honour every [pause Ns] marker as real silence.",
                "sessions": []}
    sessions = {s["id"]: s for s in data["sessions"]}
    order = [s["id"] for s in data["sessions"]]
    for draft in sorted(glob.glob(os.path.join(HERE, "drafts", f"*.{lang}.json"))):
        for s in json.load(open(draft, encoding="utf-8"))["sessions"]:
            entry = {"id": s["id"], "targetMinutes": s["targetMinutes"], "title": s["title"], "script": s["script"]}
            if s["id"] not in sessions:
                order.append(s["id"])
            sessions[s["id"]] = entry
    data["version"] = 2
    data["sessions"] = [sessions[i] for i in order]
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    return set(sessions)


def swift_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def localized(d):
    return "T(" + ", ".join(f"{l}: {swift_str(d.get(l) or d['en'])}" for l in LANGS) + ")"


def existing_symbols():
    text = open(CATALOG_SWIFT, encoding="utf-8").read()
    return dict(re.findall(r'make\("([^"]+)".*?symbol: "([^"]+)"', text, re.S))


def main():
    with_fr = merge_narration("fr")
    for lang in ("en", "de", "es", "ja", "ko"):
        if glob.glob(os.path.join(HERE, "drafts", f"*.{lang}.json")) or os.path.exists(os.path.join(NARRATION, f"narration_{lang}.json")):
            merge_narration(lang)
    symbols = existing_symbols()

    lines = [
        "//",
        "//  GuidedSessionCatalogData.swift",
        "//  CortiFree",
        "//",
        "//  GENERATED by scripts/narration/build_catalog.py from catalog_plan.json — do not edit by hand.",
        "//",
        "",
        "import SwiftUI",
        "",
        "extension GuidedSessionCatalog {",
        "    private typealias T = LocalizedText",
        "",
        "    static let generatedSessions: [GuidedSession] = [",
    ]
    included = 0
    for theme in plan["themes"]:
        lines.append(f"        // MARK: {theme['title']['en']}")
        for s in theme["sessions"]:
            if s["id"] not in with_fr:
                continue
            included += 1
            ambience = s.get("ambience")
            amb = f".{ambience}" if ambience in AMBIENCES else "nil"
            symbol = symbols.get(s["id"])
            symbol_arg = f"symbol: {swift_str(symbol)}" if symbol else f"symbol: AudioSessionCategory.{theme['id']}.symbol"
            lines.append(f"        make({swift_str(s['id'])}, .{theme['id']}, {s.get('audio_minutes', s['target_minutes'])},")
            lines.append(f"             title: {localized(s['title'])},")
            lines.append(f"             subtitle: {localized(s['subtitle'])},")
            lines.append(f"             {symbol_arg}, image: {swift_str(s['image']) if s.get('image') else 'nil'}, ambience: {amb}),")
    lines += ["    ]", "}", "", "extension AudioSessionCategory {", "    private typealias T = LocalizedText", ""]
    for key in ("title", "subtitle"):
        lines.append(f"    var generated{key.capitalize()}: LocalizedText {{")
        lines.append("        switch self {")
        for theme in plan["themes"]:
            lines.append(f"        case .{theme['id']}: return {localized(theme[key])}")
        lines.append("        }")
        lines.append("    }")
        lines.append("")
    lines.append("}")
    with open(OUT_SWIFT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    total = sum(len(t["sessions"]) for t in plan["themes"])
    print(f"Generated {included}/{total} sessions -> {OUT_SWIFT}")


if __name__ == "__main__":
    main()
